title: "Prachi Portfolio"
author: "Prachi Jain"
email: "your-email@example.com"
description: "Passionate about crafting dynamic and user-centric web experiences. Currently specializing in JavaScript and React development to build innovative and efficient solutions. Bringing the power of technology to the vibrant city of Ahmedabad, India."
baseurl: "/Simple-Portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
year: 2024
keywords: "web development, design, Jekyll"

# Menu Items
menu:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "#about"
  - title: "Portfolio"
    url: "#portfolio"
  - title: "Skills"
    url: "#skills"
  - title: "Contact"
    url: "#contact"
  - title: "Blog"
    url: "#blog"
  - title: "Download CV"
    url: "#"


# Hero Section
hero:
  name: "Prachi Jain"
  profession: "JS Developer from India"
  description: "Passionate about crafting dynamic and user-centric web experiences. Currently specializing in JavaScript and React development to build innovative and efficient solutions. Bringing the power of technology to the vibrant city of Ahmedabad, India."
  years_of_success: 6
  projects_completed: 8+
  cta_primary: "Hire Me"
  cta_secondary: "About Me"

about:
  banner_image: about-banner.png
  banner_alt: Prachi's Photo
  absolute_image: absolute-image.png
  absolute_alt: Prachi Photo
  icons:
    - name: logo-css3
      label: logo css3
    - name: logo-javascript
      label: logo javascript
    - name: logo-angular
      label: logo angular
  subtitle: "I'm a Javascript Developer"
  title: "I Develop Applications Using JS & React that Help People"
  text1: "Hi there! I'm Your Full Name, a passionate web developer from Ahmedabad, India. With over 5 years of experience in JavaScript and React, I've successfully delivered 30+ innovative projects,"
  text2: "contributing to the city's digital landscape. Let's work together to enhance your digital presence and bring your ideas to life"
  portfolio_link: "#portfolio"
  portfolio_button: "View Portfolio"

# Social Media Links
social:
  twitter: "your-twitter-handle"
  facebook: "your-facebook-page"
  linkedin: "your-linkedin-profile"
  instagram: "your-instagram-handle"

# Skills
skills:
  - name: "CSS"
    value: 95
  - name: "React"
    value: 75
  - name: "MongoDB"
    value: 90
  - name: "Python"
    value: 70
  - name: "SQL"
    value: 80
  - name: "JavaScript"
    value: 75

# Portfolio Projects
portfolio:
  - title: "Amantrika "
    subtitle: "E Invite Cards"
    image: "/assets/images/one.png"
    link: "#"
  - title: "Web Application for Desiverse"
    subtitle: "Vimeo"
    image: "/assets/images/portfolio-2.jpg"
    link: "#"
  - title: "Web Application for Desiverse"
    subtitle: "Soundcloud"
    image: "/assets/images/portfolio-3.jpg"
    link: "#"
  - title: "Web Application for Desiverse"
    subtitle: "Details"
    image: "/assets/images/portfolio-4.jpg"
    link: "#"


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
